### ISSUE TITLE
out of memory  LTX 

### ISSUE THREAD

**Issue by fallbernana123456** [newgenai79/newgenai#3]
LTX VIDEO :  I also have a 16G GPU, but I’m getting a CUDA out of memory error. Why did you only use 7G?

**Comment by newgenai79** [comment]
Surprising. How much RAM do you have? 
Post log from command prompt. Don't take screen shot, copy the content.

And also post screenshot of task manager showing GPU memory

![image](https://github.com/user-attachments/assets/40c18743-8c98-4889-a9d9-0dbbc87d80df)

**Comment by newgenai79** [comment]
@fallbernana123456 

Are you still facing the issue?

**Comment by pierre-josselin** [comment]
Hi @newgenai79,

I'm facing the same issue on my P100 16GB (and 64GB of RAM used at 50%)

```
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
  0%|                                                                                                                     | 0/50 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 2047, in process_api
    result = await self.call_function(
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1594, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 869, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\Administrateur\Documents\newgenai\LTX\LTX09_gradio.py", line 164, in generate_video
    video = pipe(
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\ltx\pipeline_ltx.py", line 710, in __call__
    noise_pred = self.transformer(
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\transformers\transformer_ltx.py", line 440, in forward
    hidden_states = block(
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\transformers\transformer_ltx.py", line 247, in forward
    attn_hidden_states = self.attn1(
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\attention_processor.py", line 588, in forward
    return self.processor(
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\transformers\transformer_ltx.py", line 84, in __call__
    hidden_states = F.scaled_dot_product_attention(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 11.45 GiB. GPU 0 has a total capacity of 15.91 GiB of which 9.78 GiB is free. Of the allocated memory 4.82 GiB is allocated by PyTorch, and 587.20 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 538.95                 Driver Version: 538.95       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P100-PCIE-16GB         TCC   | 00000000:01:00.0 Off |                    0 |
| N/A   30C    P0              30W / 250W |   6274MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      3768      C   ...rograms\Python\Python310\python.exe     6266MiB |
+---------------------------------------------------------------------------------------+
```

Edit: Tried both LTX09_gradio.py and LTX091_gradio.py

**Comment by pierre-josselin** [comment]
The problem is solved by greatly reducing the parameters (height, width, fps...) but it is strange because in your video you leave everything by default without problem with 16GB of VRAM

**Comment by nitinmukesh** [comment]
@pierre-josselin 

I only have 8 GB VRAM and 8 Gb shared RAM. I am surprised you getting OOM issue with double VRAM available.
Were you getting OOM issue using the same settings shown in video? Please create a new issue as this was closed and I missed your message.

Share the screenshot of task manager

![Screenshot 2024-12-30 231936](https://github.com/user-attachments/assets/0e651821-e7d8-4397-8cb4-32e838fd7e8c)

**Comment by pierre-josselin** [comment]
@fallbernana123456 FYI in my case the issue was that my GPU is too old and does not support newer CUDA features. But it will work in ComfyUI.
